# Generated by Django 2.0 on 2017-12-17 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('goodsID', models.IntegerField(default=100000, primary_key=True, serialize=False, verbose_name='货物编号:')),
                ('goods_name', models.CharField(default='请输入货物名称', max_length=20, verbose_name='货物名称:')),
                ('goods_price', models.IntegerField(default=0, verbose_name='货物价格:')),
                ('goods_mens', models.CharField(default='请输入计量单位', max_length=20, verbose_name='计量单位:')),
            ],
            options={
                'verbose_name_plural': '货物信息管理',
            },
        ),
        migrations.CreateModel(
            name='StoreHouse',
            fields=[
                ('stoID', models.IntegerField(default=100000, primary_key=True, serialize=False, verbose_name='仓库编号:')),
                ('sto_name', models.CharField(default='请输入仓库名称', max_length=20, verbose_name='仓库名称:')),
                ('sto_locat', models.CharField(default='请输入仓库地址', max_length=50, verbose_name='仓库地址:')),
                ('sto_ps', models.TextField(blank=True, max_length=500, null=True, verbose_name='备注:')),
            ],
            options={
                'verbose_name_plural': '仓库信息管理',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supID', models.IntegerField(default=100000, primary_key=True, serialize=False, verbose_name='供应商编号:')),
                ('sup_name', models.CharField(default='请输入供应商名称', max_length=20, verbose_name='供应商名称:')),
                ('sup_tel', models.IntegerField(null=True, verbose_name='供应商电话:')),
            ],
            options={
                'verbose_name_plural': '供应商管理',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('female', '女'), ('male', '男')], default='女', max_length=10, verbose_name='性别:')),
                ('job', models.CharField(choices=[('记帐员', '记帐员'), ('保管员', '保管员'), ('仓库主管', '仓库主管'), ('统计员', '统计员'), ('普通员工', '普通员工')], default='普通员工', max_length=10, verbose_name='职位:')),
                ('job_num', models.IntegerField(verbose_name='工号:')),
                ('account', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userinfo', to=settings.AUTH_USER_MODEL, verbose_name='用户名:')),
            ],
            options={
                'verbose_name_plural': '员工信息管理',
            },
        ),
        migrations.CreateModel(
            name='StockOut',
            fields=[
                ('goods_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.Goods', verbose_name='货物名称:')),
                ('out_date', models.DateTimeField(verbose_name='出库时间:')),
                ('out_price', models.FloatField(verbose_name='出库价格:')),
                ('out_amount', models.IntegerField(verbose_name='出库数量:')),
                ('out_ps', models.TextField(blank=True, max_length=500, null=True, verbose_name='备注:')),
                ('res_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserInfo', verbose_name='经办人姓名:')),
                ('sto_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.StoreHouse', verbose_name='所属仓库名称:')),
                ('sup_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Supplier', verbose_name='供应商名称:')),
            ],
            options={
                'verbose_name_plural': '出库单管理',
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.Goods', verbose_name='货物名称:')),
                ('storage_amount', models.IntegerField(default=0, null=True, verbose_name='现有库存:')),
                ('storage_max', models.IntegerField(default=0, null=True, verbose_name='最大库存量:')),
                ('create_date', models.DateTimeField(null=True, verbose_name='更新日期:')),
                ('goods_sto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.StoreHouse', verbose_name='所属仓库名称:')),
            ],
            options={
                'verbose_name_plural': '货物库存管理',
            },
        ),
        migrations.CreateModel(
            name='WaveHousing',
            fields=[
                ('goods_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.Goods', verbose_name='货物名称:')),
                ('in_date', models.DateTimeField(verbose_name='入库时间')),
                ('in_price', models.FloatField(verbose_name='入库价格:')),
                ('in_amount', models.IntegerField(verbose_name='入库数量:')),
                ('in_ps', models.TextField(blank=True, max_length=500, null=True, verbose_name='备注:')),
                ('res_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserInfo', verbose_name='经办人姓名:')),
                ('sto_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.StoreHouse', verbose_name='所属仓库名称:')),
                ('sup_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Supplier', verbose_name='供应商名称:')),
            ],
            options={
                'verbose_name_plural': '入库单管理',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_sto',
            field=models.ManyToManyField(null=True, to='app.StoreHouse', verbose_name='所属仓库名称:'),
        ),
    ]
