# Generated by Django 2.0 on 2017-12-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='job',
            field=models.CharField(choices=[('保管员', '保管员'), ('仓库主管', '仓库主管'), ('统计员', '统计员'), ('普通员工', '普通员工'), ('记帐员', '记帐员')], default='普通员工', max_length=10, verbose_name='职位:'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='sex',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='女', max_length=10, verbose_name='性别:'),
        ),
    ]
