# Generated by Django 2.0 on 2017-12-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171217_1950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='goods_sto',
            new_name='goods_store',
        ),
        migrations.RenameField(
            model_name='storage',
            old_name='goods',
            new_name='goods_name',
        ),
        migrations.RenameField(
            model_name='storage',
            old_name='goods_sto',
            new_name='goods_store',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='job',
            field=models.CharField(choices=[('仓库主管', '仓库主管'), ('记帐员', '记帐员'), ('保管员', '保管员'), ('统计员', '统计员'), ('普通员工', '普通员工')], default='普通员工', max_length=10, verbose_name='职位:'),
        ),
    ]
