# Generated by Django 2.0 on 2017-12-17 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20171217_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='goods_store',
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_store',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.StoreHouse', verbose_name='所属仓库名称:'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='job',
            field=models.CharField(choices=[('保管员', '保管员'), ('普通员工', '普通员工'), ('记帐员', '记帐员'), ('仓库主管', '仓库主管'), ('统计员', '统计员')], default='普通员工', max_length=10, verbose_name='职位:'),
        ),
    ]
