# Generated by Django 2.0 on 2017-12-17 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20171217_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='goods_store',
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_store',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.StoreHouse', verbose_name='所属仓库名称:'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='job',
            field=models.CharField(choices=[('普通员工', '普通员工'), ('保管员', '保管员'), ('统计员', '统计员'), ('仓库主管', '仓库主管'), ('记帐员', '记帐员')], default='普通员工', max_length=10, verbose_name='职位:'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='sex',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='女', max_length=10, verbose_name='性别:'),
        ),
    ]
