# Generated by Django 2.0 on 2017-12-19 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20171219_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_mens',
            field=models.CharField(choices=[('箱', '箱'), ('袋', '袋'), ('斤', '斤'), ('颗', '颗'), ('台', '台'), ('千克', '千克')], default='请输入计量单位', max_length=20, verbose_name='计量单位:'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.StoreHouse', verbose_name='所属仓库名称:'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='job',
            field=models.CharField(choices=[('普通员工', '普通员工'), ('统计员', '统计员'), ('仓库主管', '仓库主管'), ('保管员', '保管员'), ('记帐员', '记帐员')], default='普通员工', max_length=10, verbose_name='职位:'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='sex',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='女', max_length=10, verbose_name='性别:'),
        ),
    ]
