# Generated by Django 2.0 on 2017-12-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20171220_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_mens',
            field=models.CharField(choices=[('斤', '斤'), ('瓶', '瓶'), ('颗', '颗'), ('千克', '千克'), ('箱', '箱'), ('袋', '袋'), ('台', '台')], default='请输入计量单位', max_length=20, verbose_name='计量单位:'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='job',
            field=models.CharField(choices=[('统计员', '统计员'), ('普通员工', '普通员工'), ('保管员', '保管员'), ('仓库主管', '仓库主管'), ('记帐员', '记帐员')], default='普通员工', max_length=10, verbose_name='职位:'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='sex',
            field=models.CharField(choices=[('female', '女'), ('male', '男')], default='女', max_length=10, verbose_name='性别:'),
        ),
    ]
