# Generated by Django 2.0 on 2017-12-20 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20171220_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_mens',
            field=models.CharField(choices=[('瓶', '瓶'), ('袋', '袋'), ('台', '台'), ('颗', '颗'), ('箱', '箱'), ('斤', '斤'), ('千克', '千克')], default='请输入计量单位', max_length=20, verbose_name='计量单位:'),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='goods_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='huowu', serialize=False, to='app.Goods', verbose_name='货物名称:'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='job',
            field=models.CharField(choices=[('记帐员', '记帐员'), ('普通员工', '普通员工'), ('统计员', '统计员'), ('保管员', '保管员'), ('仓库主管', '仓库主管')], default='普通员工', max_length=10, verbose_name='职位:'),
        ),
    ]
