# Generated by Django 2.0 on 2017-12-20 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20171220_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_mens',
            field=models.CharField(choices=[('千克', '千克'), ('斤', '斤'), ('箱', '箱'), ('颗', '颗'), ('袋', '袋'), ('瓶', '瓶'), ('台', '台')], default='请输入计量单位', max_length=20, verbose_name='计量单位:'),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='goods_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.Goods', verbose_name='货物名称:'),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='sto_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.StoreHouse', verbose_name='所属仓库名称:'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='job',
            field=models.CharField(choices=[('普通员工', '普通员工'), ('记帐员', '记帐员'), ('统计员', '统计员'), ('仓库主管', '仓库主管'), ('保管员', '保管员')], default='普通员工', max_length=10, verbose_name='职位:'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='sex',
            field=models.CharField(choices=[('female', '女'), ('male', '男')], default='女', max_length=10, verbose_name='性别:'),
        ),
        migrations.AlterField(
            model_name='wavehousing',
            name='sto_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.StoreHouse', verbose_name='所属仓库名称:'),
        ),
    ]
