# Generated by Django 2.0 on 2017-12-20 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20171220_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_mens',
            field=models.CharField(choices=[('台', '台'), ('袋', '袋'), ('箱', '箱'), ('颗', '颗'), ('斤', '斤'), ('千克', '千克'), ('瓶', '瓶')], default='请输入计量单位', max_length=20, verbose_name='计量单位:'),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='goods_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stock_goods', serialize=False, to='app.Goods', verbose_name='货物名称:'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='job',
            field=models.CharField(choices=[('仓库主管', '仓库主管'), ('记帐员', '记帐员'), ('普通员工', '普通员工'), ('保管员', '保管员'), ('统计员', '统计员')], default='普通员工', max_length=10, verbose_name='职位:'),
        ),
        migrations.AlterField(
            model_name='wavehousing',
            name='goods_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='wave_goods', serialize=False, to='app.Goods', verbose_name='货物名称:'),
        ),
    ]
