# Generated by Django 2.0 on 2017-12-20 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20171220_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_mens',
            field=models.CharField(choices=[('斤', '斤'), ('台', '台'), ('袋', '袋'), ('千克', '千克'), ('瓶', '瓶'), ('箱', '箱'), ('颗', '颗')], default='请输入计量单位', max_length=20, verbose_name='计量单位:'),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='goods_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stock_goods', serialize=False, to='app.Goods', verbose_name='货物名称:'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='job',
            field=models.CharField(choices=[('普通员工', '普通员工'), ('统计员', '统计员'), ('仓库主管', '仓库主管'), ('记帐员', '记帐员'), ('保管员', '保管员')], default='普通员工', max_length=10, verbose_name='职位:'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='sex',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='女', max_length=10, verbose_name='性别:'),
        ),
        migrations.AlterField(
            model_name='wavehousing',
            name='goods_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='wave_goods', serialize=False, to='app.Goods', verbose_name='货物名称:'),
        ),
    ]
