# Generated by Django 2.0 on 2017-12-20 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20171220_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_mens',
            field=models.CharField(choices=[('千克', '千克'), ('颗', '颗'), ('箱', '箱'), ('瓶', '瓶'), ('斤', '斤'), ('袋', '袋'), ('台', '台')], default='请输入计量单位', max_length=20, verbose_name='计量单位:'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_sup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Supplier', verbose_name='供应商名称'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='job',
            field=models.CharField(choices=[('统计员', '统计员'), ('普通员工', '普通员工'), ('保管员', '保管员'), ('仓库主管', '仓库主管'), ('记帐员', '记帐员')], default='普通员工', max_length=10, verbose_name='职位:'),
        ),
    ]
