# Generated by Django 2.0 on 2017-12-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20171220_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_mens',
            field=models.CharField(choices=[('颗', '颗'), ('斤', '斤'), ('千克', '千克'), ('瓶', '瓶'), ('袋', '袋'), ('箱', '箱'), ('台', '台')], default='请输入计量单位', max_length=20, verbose_name='计量单位:'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='job',
            field=models.CharField(choices=[('仓库主管', '仓库主管'), ('统计员', '统计员'), ('记帐员', '记帐员'), ('普通员工', '普通员工'), ('保管员', '保管员')], default='普通员工', max_length=10, verbose_name='职位:'),
        ),
    ]
